name: Vinted Finder Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # toutes les 10 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installer dépendances
        run: pip install requests

      - name: Lancer le bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python vinted_finder.py
